name: test-action

on:
  push:
    branches:
      - master
    # paths:
    #   - 'scripts/abtest/tests.js'

jobs:
  build:
    name: 'Check Workflow'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      # with:
      #   path: main

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: 'npm install'
      run: |
        npm install;

    - name: 'Checking it'
      uses: './.github/actions/check'

    - name: Deploy
    uses: s0/git-publish-subdir-action@master
    with:
      github_token: '${{ secrets.GITHUB_TOKEN }}'
    env:
      REPO: git@github.com:JustinFerrara/HelloWorld.git
      BRANCH: auto-vcl-ab-test
      FOLDER: fastly/shared
      # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}


# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#     - name: 'Checkout current'
#       uses: actions/checkout@v2
#       with:
#         path: main
#       run: |
#         git status
#     - name: 'Checkout Varnish'
#       uses: actions/checkout@v2
#       with:
#         repository: businessinsider/varnish
#         path: varnish
#       run: |
#         git status
#     - name: Use Node.js 10.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 10.x
#     - name: run script
#       run: |
#         node scripts/check.js

      # npm run test:action;
    # - name: Start Fenrir and run WDIO Tests
    #   run: |
    #     FENRIR_SITE=bi CONTEXT=testing npm run test:wdio:gha
    #     killall -9 node
    #     FENRIR_SITE=insider CONTEXT=testing npm run test:wdio:gha
    # - uses: actions/upload-artifact@v1
    #   if: failure()
    #   with:
    #     name: Test results
    #     path: test/wdio/reports/.timeline
